Repository Nexters/ilab-android, pull requests merged in 2024-03, with the labels that each got.

#100 [FEAT][#97] MyPage Album 이미지 삭제 API 연결
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/datasource/DeleteMyAlbumDataSource.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/datasource/DeleteMyAlbumDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/di/DataSourceModule.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/repository/DeleteMyAlbumRepositoryImpl.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/service/ILabService.kt
  core/domain/src/main/kotlin/com/nexters/ilab/android/core/domain/repository/DeleteMyAlbumRepository.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/viewmodel/HomeSideEffect.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/viewmodel/HomeViewModel.kt
  feature/login/src/main/kotlin/com/nexters/ilab/android/feature/login/LoginScreen.kt
  feature/login/src/main/kotlin/com/nexters/ilab/android/feature/login/viewmodel/LoginViewModel.kt
  feature/myalbum/src/main/kotlin/com/nexters/ilab/android/feature/myalbum/viewmodel/MyAlbumViewModel.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/viewmodel/MyPageViewModel.kt
Labels: feature

#101 [CHORE] 코드 정리
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/datasource/FileDataSource.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/repository/ProfileRepositoryImpl.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/repository/StyleRepositoryImpl.kt
  core/domain/src/main/kotlin/com/nexters/ilab/android/core/domain/entity/CreatedProfileEntity.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Button.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/viewmodel/DummyCreatedImageUrls.kt
  feature/intro/src/main/kotlin/com/nexters/ilab/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainActivity.kt
Labels: feature

#104 [FIX] 로그인 관련 예외 처리 추가
  app/proguard-rules.pro
  build-logic/src/main/kotlin/com/nexters/ilab/android/Config.kt
  feature/intro/proguard-rules.pro
  feature/intro/src/main/kotlin/com/nexters/ilab/android/feature/intro/IntroScreen.kt
  feature/intro/src/main/kotlin/com/nexters/ilab/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/viewmodel/MyPageViewModel.kt
Labels: bug

#105 [FEAT] ComposeInvestigator 라이브러리 추가 및 적용
  build.gradle.kts
  feature/createimage/build.gradle.kts
  feature/home/build.gradle.kts
  feature/main/build.gradle.kts
  feature/myalbum/build.gradle.kts
  feature/mypage/build.gradle.kts
  feature/setting/build.gradle.kts
  feature/uploadphoto/build.gradle.kts
  gradle/libs.versions.toml
Labels: feature, gradle

#106 [FIX] Background 이미지가 언제나 화면 전체를 채우도록 수정
  app/src/main/AndroidManifest.xml
  build-logic/src/main/kotlin/com/nexters/ilab/android/Config.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Image.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeScreen.kt
  feature/login/src/main/kotlin/com/nexters/ilab/android/feature/login/LoginScreen.kt
Labels: bug, design

#110 [FEAT] 앱 로고(아이콘) 변경
  core/designsystem/src/main/res/drawable/ic_ilab_logo_110.xml
  core/designsystem/src/main/res/drawable/ic_ilab_logo_64.xml
  core/designsystem/src/main/res/drawable/ic_text_logo.xml
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeScreen.kt
Labels: design

#111 [FEAT] [#12] 이미지 생성 화면 내에 텍스트 갱신 구현
  build-logic/src/main/kotlin/com/nexters/ilab/android/Config.kt
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Button.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Dialog.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Image.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/LoadingIndicator.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/PagerIndicator.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/TopAppBar.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/CreateImageScreen.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/viewmodel/CreateImageSideEffect.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/viewmodel/CreateImageState.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/viewmodel/CreateImageViewModel.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeScreen.kt
  feature/intro/src/main/kotlin/com/nexters/ilab/android/feature/intro/IntroScreen.kt
  feature/login/src/main/kotlin/com/nexters/ilab/android/feature/login/LoginScreen.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainScreen.kt
  feature/myalbum/src/main/kotlin/com/nexters/ilab/android/feature/myalbum/MyAlbumScreen.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/viewmodel/MyPageViewModel.kt
  feature/setting/src/main/kotlin/com/nexters/ilab/android/feature/setting/SettingScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/InputStyleScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/PermissionDialog.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadCheckScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoDialog.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoScreen.kt
Labels: feature

#112 [FIX] 네비게이션 관련 프로가드 문제 임시 해결
  .github/workflows/android.yml
  app/build.gradle.kts
  app/proguard-rules.pro
  build-logic/src/main/kotlin/com/nexters/ilab/android/Android.kt
  build-logic/src/main/kotlin/com/nexters/ilab/android/Config.kt
  gradle/libs.versions.toml
Labels: bug, feature

#114 [FEAT] Firebase Crashlytics를 AndroidX Startup 라이브러리를 활용하여 초기화하는 Initializer 클래스 추가
  .github/workflows/android.yml
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/nexters/ilab/android/initializer/FirebaseCrashlyticsInitializer.kt
Labels: bug, feature

#121 [FIX] 마이 페이지 화면 AccessToken 만료, 서버 에러 대응
  build-logic/src/main/kotlin/com/nexters/ilab/android/Config.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/repository/TokenRepositoryImpl.kt
  core/datastore/src/main/kotlin/com/nexters/ilab/android/core/datastore/TokenDataSource.kt
  core/datastore/src/main/kotlin/com/nexters/ilab/android/core/datastore/TokenDataSourceImpl.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/kotlin/com/nexters/ilab/android/core/domain/repository/TokenRepository.kt
  feature/intro/src/main/kotlin/com/nexters/ilab/android/feature/intro/IntroActivity.kt
  feature/intro/src/main/kotlin/com/nexters/ilab/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/login/src/main/kotlin/com/nexters/ilab/android/feature/login/LoginActivity.kt
  feature/login/src/main/kotlin/com/nexters/ilab/android/feature/login/viewmodel/LoginViewModel.kt
  feature/main/src/main/AndroidManifest.xml
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainScreen.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/viewmodel/MyPageSideEffect.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/viewmodel/MyPageViewModel.kt
  feature/setting/src/main/kotlin/com/nexters/ilab/android/feature/setting/viewmodel/SettingViewModel.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/navigation/UploadPhotoNavigation.kt
  gradle/libs.versions.toml
Labels: bug, feature

#128 [FIX] 내 정보 API 호출 시점 변경
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/viewmodel/MyPageViewModel.kt
Labels: bug
