Repository Nexters/ilab-android, pull requests merged in 2024-02, with the labels that each got.

#25 [FEAT] [#8] 사진 가이드 화면 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  core/common/src/main/kotlin/com/nexters/ilab/android/core/common/extension/Activity.kt
  core/common/src/main/kotlin/com/nexters/ilab/android/core/common/extension/Bitmap.kt
  core/common/src/main/kotlin/com/nexters/ilab/android/core/common/extension/Context.kt
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Image.kt
  feature/camera/src/main/kotlin/com/nexters/ilab/android/feature/camera/CameraViewModel.kt
  feature/camera/src/main/kotlin/com/nexters/ilab/android/feature/camera/navigation/CameraNavigation.kt
  feature/main/build.gradle.kts
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainScreen.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainTab.kt
  feature/uploadphoto/.gitignore
  feature/uploadphoto/build.gradle.kts
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/PermissionDialog.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadCheckScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoDialog.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoSideEffect.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoState.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoViewModel.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/navigation/UploadPhotoNavigation.kt
  settings.gradle.kts
Labels: feature, design

#26 [DESIGN] Color.kt 색상 정의 변경
  core/designsystem/src/main/kotlin/com/nexters/ilab/android/core/designsystem/theme/Color.kt
Labels: design

#29 [FEAT][#27] Setting 화면 UI
  core/designsystem/src/main/res/drawable/ic_arrow_next.xml
  core/designsystem/src/main/res/values/strings.xml
  feature/setting/src/main/kotlin/com/nexters/ilab/android/feature/setting/SettingScreen.kt
Labels: feature

#30 [FEAT][#5] TopAppBar component 수정 및 에셋 추가
  core/designsystem/src/main/res/drawable/ic_home_background.png
  core/designsystem/src/main/res/drawable/ic_setting.xml
  core/designsystem/src/main/res/drawable/ic_text_logo.xml
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/TopAppBar.kt
Labels: feature

#31 [FEAT] [#4] 로그인 화면 UI 구성
  core/designsystem/src/main/kotlin/com/nexters/ilab/android/core/designsystem/theme/Color.kt
  core/designsystem/src/main/kotlin/com/nexters/ilab/android/core/designsystem/theme/Theme.kt
  core/designsystem/src/main/res/drawable/bg_login_screen.png
  core/designsystem/src/main/res/drawable/ic_ilab_logo_110.xml
  core/designsystem/src/main/res/drawable/ic_kakao.xml
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Image.kt
  feature/intro/build.gradle.kts
  feature/intro/src/main/kotlin/com/nexters/ilab/android/feature/intro/IntroActivity.kt
  feature/login/build.gradle.kts
  feature/login/src/main/kotlin/com/nexters/ilab/android/feature/login/LoginActivity.kt
  feature/login/src/main/kotlin/com/nexters/ilab/android/feature/login/LoginScreen.kt
  feature/main/build.gradle.kts
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainActivity.kt
  gradle/libs.versions.toml
Labels: feature, design

#32 [FEAT] [#9] 키워드 입력 화면 UI 구현
  core/designsystem/src/main/res/drawable/bg_home_screen.png
  core/designsystem/src/main/res/drawable/img_bad_example1.png
  core/designsystem/src/main/res/drawable/img_bad_example2.png
  core/designsystem/src/main/res/drawable/img_bad_example3.png
  core/designsystem/src/main/res/drawable/img_good_example1.png
  core/designsystem/src/main/res/drawable/img_good_example2.png
  core/designsystem/src/main/res/drawable/img_good_example3.png
  core/designsystem/src/main/res/drawable/img_keyword_dreamy.png
  core/designsystem/src/main/res/drawable/img_keyword_lonely.png
  core/designsystem/src/main/res/drawable/img_keyword_natural.png
  core/designsystem/src/main/res/drawable/img_keyword_sketch.png
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Image.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/InputKeywordScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadCheckScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoState.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoViewModel.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/navigation/UploadPhotoNavigation.kt
Labels: feature, design

#33 [FEAT] PageIndicator component 추가
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/PageIndicator.kt
Labels: feature

#34 [FIX][#27] Setting 화면 클릭 영역 수정 및 DeleteAccount onclick 추가
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainActivity.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainScreen.kt
  feature/setting/src/main/kotlin/com/nexters/ilab/android/feature/setting/SettingScreen.kt
  feature/setting/src/main/kotlin/com/nexters/ilab/android/feature/setting/navigation/SettingNavigation.kt
Labels: bug, feature

#36 [FEAT] [#11] 이미지 생성 중 화면 및 이미지 생성 완료 화면 UI 구현
  core/designsystem/src/main/res/drawable/anim_loading.gif
  core/designsystem/src/main/res/drawable/bg_create_image_complete_screen.png
  core/designsystem/src/main/res/values/strings.xml
  core/ui/build.gradle.kts
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Image.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/PageIndicator.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/PagerIndicator.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/TopAppBar.kt
  feature/intro/src/main/AndroidManifest.xml
  feature/login/src/main/AndroidManifest.xml
  feature/login/src/main/kotlin/com/nexters/ilab/android/feature/login/LoginScreen.kt
  feature/main/src/main/AndroidManifest.xml
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainScreen.kt
  feature/uploadphoto/build.gradle.kts
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/CreateImageCompleteScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/CreateImageScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/CreateImageStopDialog.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/DummyCreatedImageList.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/InputKeywordScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/PermissionDialog.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadCheckScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoState.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoViewModel.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/navigation/UploadPhotoNavigation.kt
  gradle/libs.versions.toml
Labels: feature, design

#38 [FEAT] [#9] 스타일 입력 화면으로 화면 변경 사항 반영
  core/designsystem/src/main/res/drawable/img_keyword_dreamy.png
  core/designsystem/src/main/res/drawable/img_keyword_lonely.png
  core/designsystem/src/main/res/drawable/img_keyword_natural.png
  core/designsystem/src/main/res/drawable/img_keyword_sketch.png
  core/designsystem/src/main/res/drawable/img_style_dreamlike.png
  core/designsystem/src/main/res/drawable/img_style_lonely.png
  core/designsystem/src/main/res/drawable/img_style_natural.png
  core/designsystem/src/main/res/drawable/img_style_sketch.png
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Image.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/InputStyleScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadCheckScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoState.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoViewModel.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/navigation/UploadPhotoNavigation.kt
Labels: feature, design

#39 [FEAT] [#7] 사진 가이드 화면 개인정보 수집 및 이용 동의 컴포넌트 추가
  core/designsystem/src/main/res/drawable/ic_checkbox_false.xml
  core/designsystem/src/main/res/drawable/ic_checkbox_true.xml
  core/designsystem/src/main/res/drawable/img_bad_example1.png
  core/designsystem/src/main/res/drawable/img_bad_example2.png
  core/designsystem/src/main/res/drawable/img_bad_example3.png
  core/designsystem/src/main/res/drawable/img_good_example1.png
  core/designsystem/src/main/res/drawable/img_good_example2.png
  core/designsystem/src/main/res/drawable/img_good_example3.png
  core/designsystem/src/main/res/drawable/img_guide_bad1.png
  core/designsystem/src/main/res/drawable/img_guide_bad2.png
  core/designsystem/src/main/res/drawable/img_guide_bad3.png
  core/designsystem/src/main/res/drawable/img_guide_good1.png
  core/designsystem/src/main/res/drawable/img_guide_good2.png
  core/designsystem/src/main/res/drawable/img_guide_good3.png
  core/designsystem/src/main/res/values/strings.xml
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoScreen.kt
Labels: feature, design

#49 [FEAT] [#12] 이미지 생성 화면 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/res/xml/file_paths.xml
  core/data/build.gradle.kts
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/MyClass.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/datasource/FileDataSource.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/datasource/FileDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/di/DataSourceModule.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/di/FileUtilModule.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/repository/FIleRepositoryImpl.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/util/FileUtil.kt
  core/designsystem/src/main/res/raw/lottie_loading_indicator.json
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/kotlin/com/nexters/ilab/android/core/domain/MyClass.kt
  core/domain/src/main/kotlin/com/nexters/ilab/android/core/domain/repository/FileRepository.kt
  core/ui/build.gradle.kts
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/LoadingIndicator.kt
  feature/createimage/build.gradle.kts
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/CreateImageCompleteScreen.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/CreateImageScreen.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/CreateImageStopDialog.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/navigation/CreateImageNavigation.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/viewmodel/CraeteImageSideEffect.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/viewmodel/CreateImageState.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/viewmodel/CreateImageViewModel.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/viewmodel/DummyCreatedImageUrls.kt
  feature/main/build.gradle.kts
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/DummyCreatedImageList.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/InputStyleScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadCheckScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoSideEffect.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/navigation/UploadPhotoNavigation.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/viewmodel/UploadPhotoSideEffect.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/viewmodel/UploadPhotoState.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/viewmodel/UploadPhotoViewModel.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: feature, design

#52 [FEAT] [#9] 사진 가이드 화면 구현
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/di/DataSourceModule.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/repository/PrivacyPolicyRepositoryImpl.kt
  core/datastore/src/main/kotlin/com/nexters/ilab/android/core/datastore/PrivacyPolicyDataSource.kt
  core/datastore/src/main/kotlin/com/nexters/ilab/android/core/datastore/PrivacyPolicyDataSourceImpl.kt
  core/datastore/src/main/kotlin/com/nexters/ilab/android/core/datastore/TokenDataSource.kt
  core/datastore/src/main/kotlin/com/nexters/ilab/android/core/datastore/TokenDataSourceImpl.kt
  core/datastore/src/main/kotlin/com/nexters/ilab/android/core/datastore/di/DataStoreModule.kt
  core/datastore/src/main/kotlin/com/nexters/ilab/android/core/datastore/di/DataStoreQualifier.kt
  core/domain/build.gradle.kts
  core/domain/src/main/kotlin/com/nexters/ilab/android/core/domain/repository/PrivacyPolicyRepository.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/viewmodel/UploadPhotoState.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/viewmodel/UploadPhotoViewModel.kt
  gradle/libs.versions.toml
Labels: feature

#50 [FEAT][#13] MyPage 화면 UI
  core/designsystem/src/main/res/drawable/ic_more.xml
  core/designsystem/src/main/res/drawable/ic_no_img.png
  core/designsystem/src/main/res/drawable/ic_profile.png
  core/designsystem/src/main/res/values/strings.xml
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainScreen.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/MyAlbumImageScreen.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/MyPageSideEffect.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/MyPageState.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/MyPageViewModel.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/navigation/MyPageNavigation.kt
Labels: feature

#53 [FEAT] [#51] Navigation Bar UI 구현
  core/designsystem/src/main/res/drawable/ic_home.xml
  core/designsystem/src/main/res/drawable/ic_upload.xml
  core/designsystem/src/main/res/drawable/ic_upload_photo.png
  feature/main/build.gradle.kts
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainScreen.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainTab.kt
Labels: design

#54 [FEAT][#5] 홈 화면 UI
  core/designsystem/src/main/res/drawable/bg_create_image_complete_screen.png
  core/designsystem/src/main/res/drawable/bg_home_screen.png
  core/designsystem/src/main/res/drawable/bg_login_screen.png
  core/designsystem/src/main/res/drawable/bg_my_page_screen.png
  core/designsystem/src/main/res/drawable/ic_upload_photo.png
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Image.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/CreateImageCompleteScreen.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeSideEffect.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeState.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/navigation/HomeNavigation.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainScreen.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/MyAlbumImageScreen.kt
  feature/setting/src/main/kotlin/com/nexters/ilab/android/feature/setting/SettingScreen.kt
Labels: feature

#59 [FEAT] [#16] 스플래시 화면 구현
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/res/drawable/bg_splash_screen.png
  core/designsystem/src/main/res/drawable/ic_ilab_logo_64.xml
  core/designsystem/src/main/res/drawable/ic_splash.png
  core/designsystem/src/main/res/values/themes.xml
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Image.kt
  feature/intro/build.gradle.kts
  feature/intro/src/main/AndroidManifest.xml
  feature/intro/src/main/kotlin/com/nexters/ilab/android/feature/intro/IntroActivity.kt
  feature/intro/src/main/kotlin/com/nexters/ilab/android/feature/intro/IntroScreen.kt
  feature/login/src/main/AndroidManifest.xml
  feature/main/src/main/AndroidManifest.xml
Labels: design

#71 [FEAT] Project Clean Up
  core/common/build.gradle.kts
  core/common/src/main/kotlin/com/nexters/ilab/android/core/common/extension/NavBackStackEntry.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/TopAppBar.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/navigation/CreateImageNavigation.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/navigation/MyPageNavigation.kt
  feature/privacypolicy/build.gradle.kts
  feature/privacypolicy/src/main/kotlin/com/nexters/ilab/android/feature/privacypolicy/PrivacyPolicyScreen.kt
  feature/privacypolicy/src/main/kotlin/com/nexters/ilab/android/feature/privacypolicy/PrivacyPolicyViewModel.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/navigation/UploadPhotoNavigation.kt
  gradle.properties
Labels: feature

#73 [FEAT] 계정 삭제 다이얼로그, 네트워크 에러 다이얼로그 구현
  core/designsystem/src/main/res/drawable/ic_network_error.xml
  core/designsystem/src/main/res/drawable/ic_warning.xml
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Dialog.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/CreateImageScreen.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/CreateImageStopDialog.kt
  feature/setting/src/main/kotlin/com/nexters/ilab/android/feature/setting/SettingScreen.kt
  feature/setting/src/main/kotlin/com/nexters/ilab/android/feature/setting/SettingViewModel.kt
  feature/setting/src/main/kotlin/com/nexters/ilab/android/feature/setting/viewmodel/SettingSideEffect.kt
  feature/setting/src/main/kotlin/com/nexters/ilab/android/feature/setting/viewmodel/SettingState.kt
  feature/setting/src/main/kotlin/com/nexters/ilab/android/feature/setting/viewmodel/SettingViewModel.kt
Labels: feature, design

#74 [FIX][#6] Home 화면 UI 수정
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeScreen.kt
Labels: bug, design

#76 [FEAT][#28] Setting 화면 App Version
  feature/setting/src/main/kotlin/com/nexters/ilab/android/feature/setting/SettingScreen.kt
  feature/setting/src/main/kotlin/com/nexters/ilab/android/feature/setting/viewmodel/SettingViewModel.kt
Labels: feature

#77 [FIX][#14] My Page 화면 bottom padding 수정
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/MyPageScreen.kt
Labels: bug, design

#75 [FEAT] 스타일로 프로필 생성하기 버튼을 눌러 사진 업로드 화면으로 이동
  core/designsystem/src/main/res/drawable/ic_check.xml
  core/designsystem/src/main/res/drawable/img_style_dreamlike.png
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Image.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/navigation/HomeNavigation.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/InputStyleScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/model/StyleModel.kt
Labels: feature

#78 [FEAT] 스타일 입력 화면 API 연동
  app/src/main/kotlin/com/nexters/ilab/android/initializer/TimberInitializer.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/datasource/StyleDataSource.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/datasource/StyleDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/di/ApiModule.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/di/DataSourceModule.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/mapper/EntityToResponse.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/mapper/ResponseToEntity.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/repository/StyleRepositoryImpl.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/response/StyleResponse.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/service/ILabService.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/service/LoginService.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/util/RunSuspendCatching.kt
  core/domain/build.gradle.kts
  core/domain/src/main/kotlin/com/nexters/ilab/android/core/domain/entity/StyleEntity.kt
  core/domain/src/main/kotlin/com/nexters/ilab/android/core/domain/repository/StyleRepository.kt
  core/network/src/main/kotlin/com/nexters/ilab/android/core/network/di/NetworkModule.kt
  core/network/src/main/kotlin/com/nexters/ilab/android/core/network/service/ILabService.kt
  core/network/src/main/kotlin/com/nexters/ilab/android/core/network/service/LoginService.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Image.kt
  feature/uploadphoto/build.gradle.kts
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/InputStyleScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/model/StyleModel.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/viewmodel/UploadPhotoState.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/viewmodel/UploadPhotoViewModel.kt
  gradle/libs.versions.toml
Labels: feature

#79 [FEAT][#6] Home 화면 Profile Dialog 추가
  core/designsystem/src/main/res/drawable/bg_img_dim.xml
  core/designsystem/src/main/res/drawable/ic_profile_close.xml
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeState.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeViewModel.kt
Labels: feature

#82 [FIX] LoadingIndicator 수정
  core/designsystem/src/main/res/raw/lottie_loading_indicator.json
  core/domain/src/main/kotlin/com/nexters/ilab/android/core/domain/entity/ProfileEntity.kt
  core/ui/build.gradle.kts
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/LoadingIndicator.kt
  gradle/libs.versions.toml
Labels: design

#83 [FEAT][#6] Home 화면 Style API 연결
  feature/home/build.gradle.kts
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeState.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeViewModel.kt
Labels: feature

#86 [FEAT] 홈화면 내에 스타일로 프로필 생성하기 버튼을 통해, 스타일 입력화면내에 선택한 스타일이 체크되도록 구현
  core/common/build.gradle.kts
  core/common/src/main/kotlin/com/nexters/ilab/android/core/common/HandleException.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/datasource/AuthDataSource.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/datasource/AuthDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/repository/AuthRepositoryImpl.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/service/AuthService.kt
  feature/home/build.gradle.kts
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/viewmodel/HomeSideEffect.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/viewmodel/HomeState.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/viewmodel/HomeViewModel.kt
  feature/login/src/main/kotlin/com/nexters/ilab/android/feature/login/LoginScreen.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainScreen.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/viewmodel/MyPageViewModel.kt
  feature/uploadphoto/build.gradle.kts
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/InputStyleScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/navigation/UploadPhotoNavigation.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/viewmodel/UploadPhotoViewModel.kt
Labels: feature

#87 [FEAT][#6] Home 화면 Profile API 연결
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/datasource/ProfileDataSource.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/datasource/ProfileDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/di/DataSourceModule.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/mapper/ResponseToEntity.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/repository/ProfileRepositoryImpl.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/response/ProfileResponse.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/service/ILabService.kt
  core/designsystem/src/main/res/drawable/bg_img_dim_large.xml
  core/designsystem/src/main/res/drawable/bg_img_dim_small.xml
  core/domain/src/main/kotlin/com/nexters/ilab/android/core/domain/repository/ProfileRepository.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/viewmodel/HomeViewModel.kt
Labels: feature, design

#89 [FEAT] [#85] 다크모드 구현
  app/build.gradle.kts
  app/src/main/res/values/colors.xml
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/kotlin/com/nexters/ilab/android/core/designsystem/theme/Color.kt
  core/designsystem/src/main/kotlin/com/nexters/ilab/android/core/designsystem/theme/Theme.kt
  core/designsystem/src/main/res/drawable/bg_home_screen_dark.png
  core/designsystem/src/main/res/drawable/bg_my_page_screen_dark.png
  core/designsystem/src/main/res/values/splash.xml
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Button.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Dialog.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/Image.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/PagerIndicator.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/TopAppBar.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/CreateImageCompleteScreen.kt
  feature/createimage/src/main/kotlin/com/nexters/ilab/feature/createimage/CreateImageScreen.kt
  feature/home/src/main/kotlin/com/nexters/ilab/android/feature/home/HomeScreen.kt
  feature/intro/src/main/AndroidManifest.xml
  feature/login/src/main/kotlin/com/nexters/ilab/android/feature/login/LoginScreen.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainActivity.kt
  feature/main/src/main/kotlin/com/nexters/ilab/android/feature/main/MainScreen.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/MyAlbumImageScreen.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/MyPageScreen.kt
  feature/setting/src/main/kotlin/com/nexters/ilab/android/feature/setting/SettingScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/InputStyleScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/PermissionDialog.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadCheckScreen.kt
  feature/uploadphoto/src/main/kotlin/com/nexters/ilab/android/feature/uploadphoto/UploadPhotoScreen.kt
Labels: feature, design

#91 [FEAT] [#88] 자동 로그인 구현
  feature/intro/src/main/kotlin/com/nexters/ilab/android/feature/intro/IntroActivity.kt
  feature/intro/src/main/kotlin/com/nexters/ilab/android/feature/intro/IntroScreen.kt
  feature/intro/src/main/kotlin/com/nexters/ilab/android/feature/intro/IntroViewModel.kt
  feature/intro/src/main/kotlin/com/nexters/ilab/android/feature/intro/viewmodel/IntroSideEffect.kt
  feature/intro/src/main/kotlin/com/nexters/ilab/android/feature/intro/viewmodel/IntroState.kt
  feature/intro/src/main/kotlin/com/nexters/ilab/android/feature/intro/viewmodel/IntroViewModel.kt
  feature/login/src/main/kotlin/com/nexters/ilab/android/feature/login/viewmodel/LoginViewModel.kt
Labels: feature

#94 [FEAT] TokenInterceptor 가 포함된 OkHttpClient 와 포함되지 않은 OkHttpClient 를 분리
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/di/ApiModule.kt
  core/network/src/main/kotlin/com/nexters/ilab/android/core/network/di/NetworkModule.kt
  core/network/src/main/kotlin/com/nexters/ilab/android/core/network/di/RetrofitQualifier.kt
  core/ui/src/main/kotlin/com/nexters/ilab/core/ui/component/LoadingIndicator.kt
  feature/login/src/main/kotlin/com/nexters/ilab/android/feature/login/LoginScreen.kt
Labels: bug, feature

#90 [FEAT][#14] MyPage Album API 연결
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/mapper/ResponseToEntity.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/response/UserInfoResponse.kt
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/kotlin/com/nexters/ilab/android/core/domain/entity/UserInfoEntity.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/MyAlbumImageScreen.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/viewmodel/MyPageSideEffect.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/viewmodel/MyPageState.kt
  feature/mypage/src/main/kotlin/com/nexters/ilab/android/feature/mypage/viewmodel/MyPageViewModel.kt
Labels: feature, design

#96 [FIX] Auth API(유저 정보, 로그아웃, 계정 삭제) 변경 사항 반영
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/datasource/AuthDataSource.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/datasource/AuthDataSourceImpl.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/repository/AuthRepositoryImpl.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/request/AuthRequest.kt
  core/data/src/main/kotlin/com/nexters/ilab/android/core/data/service/AuthService.kt
  core/designsystem/src/main/kotlin/com/nexters/ilab/android/core/designsystem/theme/Theme.kt
Labels: feature, design
